go_library(
    name = "forgewrap",
    srcs = ["forgewrap.go"],
    visibility = ["//tools/please_sol/..."],
)

go_test(
    name = "forgewrap_test",
    srcs = ["forgewrap_test.go"],
    deps = [":forgewrap"],
)
